"""Cause-driven live test for one persistent offline DLSS-G 2X worker."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import struct
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.backends.dlssg_worker import DlssgWorker  # noqa: E402

WIDTH = 256
HEIGHT = 256
SENTINEL = bytes((3, 5, 7, 255)) * (WIDTH * HEIGHT)
SENTINEL_SHA = hashlib.sha256(SENTINEL).hexdigest().upper()


def color_frame(square_x: int) -> bytes:
    background = bytes((16, 24, 32, 255))
    square = bytes((240, 220, 64, 255))
    output = bytearray(background * (WIDTH * HEIGHT))
    for y in range(96, 160):
        for x in range(square_x, square_x + 64):
            offset = (y * WIDTH + x) * 4
            output[offset : offset + 4] = square
    return bytes(output)


def motion_frame(square_x: int, motion_x: float) -> bytes:
    output = bytearray(WIDTH * HEIGHT * 4)
    value = struct.pack("<ee", motion_x, 0.0)
    for y in range(96, 160):
        for x in range(square_x, square_x + 64):
            offset = (y * WIDTH + x) * 4
            output[offset : offset + 4] = value
    return bytes(output)


def validate_output(output: bytes, current: bytes, prior_hash: str | None) -> dict[str, object]:
    digest = hashlib.sha256(output).hexdigest().upper()
    if len(output) != WIDTH * HEIGHT * 4:
        raise AssertionError(f"generated byte count {len(output)}")
    if not any(output):
        raise AssertionError("generated output is all zero")
    if len(set(output)) == 1:
        raise AssertionError("generated output is constant")
    if output == SENTINEL:
        raise AssertionError("generated output is stale sentinel")
    if output == current:
        raise AssertionError("generated output duplicates current input")
    if prior_hash == digest:
        raise AssertionError("consecutive moving outputs have identical hashes")
    return {
        "sha256": digest,
        "bytes": len(output),
        "minimum": min(output),
        "maximum": max(output),
        "mean": sum(output) / len(output),
        "identical_to_current": False,
        "identical_to_sentinel": False,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--worker", type=Path, required=True)
    parser.add_argument("--community-runtime", type=Path, required=True)
    parser.add_argument("--official-runtime-dir", type=Path, required=True)
    parser.add_argument(
        "--manifest",
        type=Path,
        default=ROOT / "native" / "dlssg_sm86_offline" / "runtime" / "output" / "persistent_manifest.json",
    )
    args = parser.parse_args()
    records: list[dict[str, object]] = []
    generated = 0
    diagnostics: tuple[str, ...] = ()
    client = DlssgWorker(
        args.worker.resolve(),
        args.community_runtime.resolve(),
        args.official_runtime_dir.resolve(),
        diagnostic_callback=lambda line: print(line, file=sys.stderr, flush=True),
    )
    try:
        client.start()
        create = client.create(WIDTH, HEIGHT)
        assert create["maximum_generated_frames"] >= 1
        prior_hash = None
        for frame_id in range(16):
            x = 32 + frame_id * 4
            color = color_frame(x)
            motion = motion_frame(x, 0.0 if frame_id == 0 else -4.0)
            result = client.process(frame_id, color, motion, reset=frame_id == 0)
            record: dict[str, object] = {
                "frame_id": frame_id,
                "sequence": 1,
                "reset_only": result.reset_only,
                "disable": result.disable_interpolation,
                "timings_ms": {
                    "upload": result.upload_ms,
                    "evaluate_cpu": result.evaluate_cpu_ms,
                    "gpu_wait": result.gpu_wait_ms,
                    "readback": result.readback_ms,
                    "total": result.total_process_ms,
                },
            }
            if frame_id == 0:
                assert result.reset_only and not result.output
            else:
                assert result.generated_count == 1 and result.disable_interpolation == 0
                details = validate_output(result.output, color, prior_hash)
                prior_hash = str(details["sha256"])
                record.update(details)
                generated += 1
            records.append(record)

        client.reset_history()
        prior_hash = None
        for frame_id in range(16, 21):
            step = frame_id - 16
            x = 152 - step * 4
            color = color_frame(x)
            motion = motion_frame(x, 0.0 if step == 0 else 4.0)
            result = client.process(frame_id, color, motion)
            record = {
                "frame_id": frame_id,
                "sequence": 2,
                "reset_only": result.reset_only,
                "disable": result.disable_interpolation,
                "timings_ms": {
                    "upload": result.upload_ms,
                    "evaluate_cpu": result.evaluate_cpu_ms,
                    "gpu_wait": result.gpu_wait_ms,
                    "readback": result.readback_ms,
                    "total": result.total_process_ms,
                },
            }
            if step == 0:
                assert result.reset_only and not result.output
            else:
                assert result.generated_count == 1 and result.disable_interpolation == 0
                details = validate_output(result.output, color, prior_hash)
                prior_hash = str(details["sha256"])
                record.update(details)
                generated += 1
            records.append(record)
    finally:
        client.close()
        diagnostics = client.diagnostics

    close_lines = [line for line in diagnostics if line.startswith("WORKER_CLOSE ")]
    if len(close_lines) != 1:
        raise AssertionError(f"missing worker lifecycle counters: {close_lines}")
    match = re.search(r"initCount=(\d+) createCount=(\d+) evaluateCount=(\d+) generatedCount=(\d+)", close_lines[0])
    if not match:
        raise AssertionError(close_lines[0])
    counts = {name: int(value) for name, value in zip(("init", "create", "evaluate", "generated"), match.groups())}
    assert counts == {"init": 1, "create": 1, "evaluate": 21, "generated": 19}
    assert generated == 19
    args.manifest.parent.mkdir(parents=True, exist_ok=True)
    manifest = {
        "protocol_version": 1,
        "process_count": 1,
        "feature_instances": counts["create"],
        "input_frames": 21,
        "generated_outputs": generated,
        "sequence_one_generated": 15,
        "sequence_two_generated": 4,
        "sentinel_sha256": SENTINEL_SHA,
        "lifecycle_counts": counts,
        "frames": records,
    }
    args.manifest.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(json.dumps({"status": "PASS", "manifest": str(args.manifest), "counts": counts}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
